#!/usr/bin/env bash

_PREPARA() {
     cd /usr/src
     rm -rf linux
     ln -s linux-*-gentoo linux
     cd linux
     echo "Copie a configuração do kernel e rode 'make menuconfig'."
}

_COMPILA() {
     # make localmodconfig
     make -s -j4 bzImage modules
     make -s -j4 modules_install
     make install
     grub-mkconfig -o /boot/grub/grub.cfg
}

case $1 in
     --prepare) _PREPARA ;;
     --compile) _COMPILA ;;
esac
