#!/usr/bin/env bash

_PREPARA() {
     cp config-arch /usr/src/linux/.config
     cd /usr/src/linux
     echo "Rode as seguintes linhas de comando;
                ---------------------------
                eselect kernel list
                eselect kernel set <number>
                ---------------------------"
}

_COMPILA() {
     make -s -j5 bzImage modules
     make -s -j5 modules_install
     make install
     grub-mkconfig -o /boot/grub/grub.cfg
}

case $1 in
     --prepare) _PREPARA ;;
     --compile) _COMPILA ;;
esac
